version: "3"

services:
  backend:
    image: node:18.12.1-alpine
    container_name: back
    ports:
      - "8080:8080"
    working_dir: /home/node/app
    volumes:
      - type: bind
        source: ./backend
        target: /home/node/app
    depends_on:
      - 'db'
    command: sh -c "npm run start"

  frontend:
    image: node:18.12.1-alpine
    container_name: front
    ports:
      - "3000:3000"
    working_dir: /home/node/app
    volumes:
      - type: bind
        source: ./frontend
        target: /home/node/app
    depends_on:
      - 'backend'
    command: sh -c "npm run start"

  db:
    image: postgres:15.1-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sample_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db_volume:/var/lib/postgresql/data
volumes:
  db_volume:
